version: '3.8'

services:
  next:
    container_name: aimcup-next
    build:
      context: .
      dockerfile: ./build.next.Dockerfile
    restart: always
    ports:
      - "4000:3000"
    networks:
      - default

networks:
  default:
    external: true
    name: aimcup-network